namespace PeerSharp.Interfaces;

/// <summary>
/// Provides access to alerts generated by the BitTorrent client.
/// </summary>
/// <remarks>
/// <para>
/// <b>IAlerts vs ITorrentEvents - When to Use Which:</b>
/// </para>
/// <para>
/// Use <see cref="IAlerts"/> (this interface) when you need:
/// <list type="bullet">
///   <item>Centralized monitoring of all torrents from a single location</item>
///   <item>Background processing with controlled polling intervals</item>
///   <item>Batch processing of multiple alerts at once</item>
///   <item>Decoupled event handling (alerts are queued, not synchronous)</item>
/// </list>
/// </para>
/// <para>
/// Use <see cref="ITorrentEvents"/> when you need:
/// <list type="bullet">
///   <item>Immediate, synchronous callbacks for a specific torrent</item>
///   <item>Per-torrent event subscriptions with strong typing</item>
///   <item>UI updates that require instant responsiveness</item>
///   <item>Simpler callback-based programming model</item>
/// </list>
/// </para>
/// <para>
/// Both mechanisms can be used simultaneously. Alerts are fire-and-forget (queued),
/// while events are synchronous callbacks on the posting thread.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Polling approach
/// engine.Alerts.RegisterAlerts((uint)(AlertId.TorrentFinished | AlertId.TorrentError));
/// while (running)
/// {
///     foreach (var alert in engine.Alerts.PopAlerts())
///     {
///         Console.WriteLine($"Alert: {alert.Id}");
///     }
///     await Task.Delay(1000);
/// }
///
/// // Async streaming approach
/// await foreach (var alert in engine.Alerts.GetAlertsAsync(cancellationToken))
/// {
///     Console.WriteLine($"Alert: {alert.Id}");
/// }
/// </code>
/// </example>
public interface IAlerts
{
    /// <summary>
    /// Asynchronously streams alerts as they become available.
    /// </summary>
    /// <param name="pollingInterval">
    /// The interval between polling attempts when no alerts are available.
    /// Defaults to 100 milliseconds.
    /// </param>
    /// <param name="cancellationToken">Token to cancel the enumeration.</param>
    /// <returns>An async enumerable of alerts.</returns>
    /// <remarks>
    /// This method polls the alert queue at the specified interval and yields
    /// alerts as they become available. Use this for continuous monitoring
    /// scenarios where you want to process alerts asynchronously.
    /// </remarks>
    /// <example>
    /// <code>
    /// await foreach (var alert in engine.Alerts.GetAlertsAsync(cancellationToken: cts.Token))
    /// {
    ///     if (alert is TorrentFinishedAlert finished)
    ///     {
    ///         Console.WriteLine($"Torrent finished: {finished.Torrent.Name}");
    ///     }
    /// }
    /// </code>
    /// </example>
    IAsyncEnumerable<Alert> GetAlertsAsync(
        TimeSpan? pollingInterval = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Dequeues and returns all alerts currently in the queue.
    /// </summary>
    /// <returns>A list of alerts. Returns an empty list if no alerts are queued.</returns>
    /// <remarks>
    /// This method is thread-safe and non-blocking. For async consumption,
    /// consider using <see cref="GetAlertsAsync"/> instead.
    /// </remarks>
    List<Alert> PopAlerts();

    /// <summary>
    /// Registers which types of alerts should be queued.
    /// Use a bitwise OR of <see cref="AlertId"/> values.
    /// </summary>
    /// <param name="alertMask">The mask of AlertId values to enable.</param>
    /// <example>
    /// <code>
    /// // Register for specific alerts
    /// alerts.RegisterAlerts((uint)(AlertId.TorrentFinished | AlertId.ProgressChanged));
    ///
    /// // Register for all torrent alerts
    /// alerts.RegisterAlerts((uint)AlertCategory.Torrent);
    /// </code>
    /// </example>
    void RegisterAlerts(uint alertMask);
}
